repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending

- repo: https://github.com/psf/black
  rev: 21.6b0
  hooks:
  - id: black
